/** Mall admin portal with branding/layout/versioning, queues, map and parking management. */
import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
const API='http://localhost:4000';
async function api(path,opts={}){const t=localStorage.getItem('accessToken');const tenant=localStorage.getItem('tenantId');const h={'Content-Type':'application/json',...(opts.headers||{})};if(t)h.Authorization=`Bearer ${t}`;if(tenant)h['X-Tenant-ID']=tenant;const r=await fetch(API+path,{...opts,headers:h});if(!r.ok)throw new Error(await r.text());return r.json();}
function App(){const [branding,setBranding]=useState([]);const [layout,setLayout]=useState([]);const [reports,setReports]=useState([]);const [verify,setVerify]=useState([]);const [floors,setFloors]=useState([]);const [zones,setZones]=useState([]);
const reload=()=>{api('/mall-admin/branding').then(setBranding).catch(()=>{});api('/mall-admin/layout').then(setLayout).catch(()=>{});api('/mall-admin/reports').then(setReports).catch(()=>{});api('/mall-admin/verification-requests').then(setVerify).catch(()=>{});api('/mall-admin/floors').then(setFloors).catch(()=>{});api('/mall-admin/parking-zones').then(setZones).catch(()=>{});};
useEffect(reload,[]);
return <main style={{fontFamily:'Inter,sans-serif',padding:16}}><h1>Mall Admin</h1><section><h3>Branding</h3><button onClick={async()=>{await api('/mall-admin/branding',{method:'POST',body:JSON.stringify({primary:'#111',secondary:'#eee',publish:true})});reload();}}>Publish Branding</button>{branding.map(b=><div key={b.id}>v{b.version_no}</div>)}</section><section><h3>Layout Builder</h3><button onClick={async()=>{await api('/mall-admin/layout',{method:'POST',body:JSON.stringify({modules:['featuredStores','events'],publish:true})});reload();}}>Publish Layout</button>{layout.map(l=><div key={l.id}>v{l.version_no}</div>)}</section><section><h3>Verification Queue</h3>{verify.map(v=><div key={v.id}>{v.store_id} {v.status}<button onClick={()=>api(`/mall-admin/verification-requests/${v.id}/decision`,{method:'POST',body:JSON.stringify({status:'approved',note:'ok'})}).then(reload)}>Approve</button></div>)}</section><section><h3>Moderation Queue</h3>{reports.map(r=><div key={r.id}>{r.reason} {r.status}<button onClick={()=>api(`/mall-admin/moderation/${r.id}/action`,{method:'POST',body:JSON.stringify({action:'warn',note:'policy'})}).then(reload)}>Action</button></div>)}</section><section><h3>Map Editor</h3><button onClick={()=>api('/mall-admin/floors',{method:'POST',body:JSON.stringify({label:'L1',levelNo:1})}).then(reload)}>Add Floor</button>{floors.map(f=><div key={f.id}>{f.label}</div>)}</section><section><h3>Parking Admin</h3><button onClick={()=>api('/mall-admin/parking-zones',{method:'POST',body:JSON.stringify({zoneCode:'A1',levelLabel:'L1',capacity:100})}).then(reload)}>Add Zone</button>{zones.map(z=><div key={z.id}>{z.zone_code}<button onClick={()=>api(`/mall-admin/parking-zones/${z.id}/snapshots`,{method:'POST',body:JSON.stringify({occupied:40})})}>Snapshot</button></div>)}</section></main>}
createRoot(document.getElementById('root')).render(<App/>);
