PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', plan TEXT NOT NULL DEFAULT 'standard', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, global_role TEXT NOT NULL DEFAULT 'customer', is_email_verified INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_tenant_memberships (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS stores (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', floor_label TEXT, is_verified INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS store_users (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS refresh_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT NOT NULL, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS password_reset_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, tenant_id TEXT, actor_user_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tenant_branding_versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, version_no INTEGER NOT NULL, payload TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tenant_layout_versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, version_no INTEGER NOT NULL, payload TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS store_categories (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, category_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS store_hours (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, weekday INTEGER NOT NULL, open_at TEXT NOT NULL, close_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS store_contact_links (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, type TEXT NOT NULL, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS store_gallery (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, media_url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS promotions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, title TEXT NOT NULL, promo_code TEXT NOT NULL, starts_at TEXT, ends_at TEXT);
CREATE TABLE IF NOT EXISTS promotion_redemptions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, promotion_id TEXT NOT NULL, user_id TEXT NOT NULL, redeemed_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT, title TEXT NOT NULL, starts_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS event_rsvps (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, event_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS store_reviews (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, user_id TEXT NOT NULL, rating INTEGER NOT NULL, body TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS review_responses (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, review_id TEXT NOT NULL, responder_user_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conversation_threads (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, thread_id TEXT NOT NULL, sender_user_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, author_user_id TEXT NOT NULL, body TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'post', expires_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS post_media (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, media_url TEXT NOT NULL, media_type TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS post_likes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS post_comments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, user_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS post_shares (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS hashtags (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, tag TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS post_hashtags (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, hashtag_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mentions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, post_id TEXT NOT NULL, mentioned_user_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, reporter_user_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS moderation_actions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, report_id TEXT NOT NULL, moderator_user_id TEXT NOT NULL, action TEXT NOT NULL, note TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS store_verification_requests (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT NOT NULL, requested_by TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', decided_by TEXT, decision_note TEXT, decided_at TEXT);
CREATE TABLE IF NOT EXISTS parking_zones (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, zone_code TEXT NOT NULL, level_label TEXT NOT NULL, capacity INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS parking_occupancy_snapshots (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, parking_zone_id TEXT NOT NULL, occupied INTEGER NOT NULL, captured_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS car_locations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, parking_zone_id TEXT NOT NULL, notes TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS floors (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, label TEXT NOT NULL, level_no INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pois (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, floor_id TEXT NOT NULL, store_id TEXT, kind TEXT NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS path_nodes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, floor_id TEXT NOT NULL, x REAL NOT NULL, y REAL NOT NULL);
CREATE TABLE IF NOT EXISTS path_edges (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, node_a_id TEXT NOT NULL, node_b_id TEXT NOT NULL, distance_meters REAL NOT NULL, accessible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS saved_routes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, from_poi_id TEXT NOT NULL, to_poi_id TEXT NOT NULL, route_json TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS crm_segments (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', rule_json TEXT NOT NULL DEFAULT '{}', created_by TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS crm_campaigns (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, segment_id TEXT, channel TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', content TEXT NOT NULL DEFAULT '{}', scheduled_at TEXT, created_by TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, user_id TEXT, store_id TEXT, event_name TEXT NOT NULL, properties TEXT NOT NULL DEFAULT '{}', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_daily_rollups (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT, metric_date TEXT NOT NULL, metric_name TEXT NOT NULL, metric_value REAL NOT NULL, UNIQUE(tenant_id,store_id,metric_date,metric_name));
CREATE TABLE IF NOT EXISTS analytics_hourly_rollups (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT, metric_hour TEXT NOT NULL, metric_name TEXT NOT NULL, metric_value REAL NOT NULL, UNIQUE(tenant_id,store_id,metric_hour,metric_name));
CREATE TABLE IF NOT EXISTS analytics_kpis (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, store_id TEXT, kpi_key TEXT NOT NULL, kpi_value REAL NOT NULL, calculated_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(tenant_id,store_id,kpi_key));
